/**
<<<<<<< HEAD
 * @generated by scripts/set-rn-version.js
 *
 * Copyright (c) Meta Platforms, Inc. and affiliates.
=======
 * @generated by scripts/bump-oss-version.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
>>>>>>> tvos-v0.66.3
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @flow strict
 */

exports.version = {
  major: 0,
  minor: 68,
  patch: 0,
  prerelease: null,
};
