require_relative '../scripts/react_native_pods'

source 'https://cdn.cocoapods.org/'
platform :tvos, '12.0'

if ENV['USE_FRAMEWORKS'] == '1'
  puts "Installing pods with use_frameworks!"
  use_frameworks!
end

def pods()
  project 'RNTesterPods.xcodeproj'

  # Enable TurboModule
  use_react_native!(path: "..")
  pod 'ReactCommon/turbomodule/samples', :path => '../ReactCommon'

  # Additional Pods which aren't included in the default Podfile
  pod 'React-ART', :path => '../Libraries/ART'
  pod 'React-RCTPushNotification', :path => '../Libraries/PushNotificationIOS'
  pod 'Yoga',:path => '../ReactCommon/yoga', :modular_headers => true
  # Additional Pods which are classed as unstable
  #
  # To use fabric: add `fabric_enabled` option to the use_react_native method above, like below
  # use_react_native!(path: "..", fabric_enabled: true)
end

target 'RNTester' do
  pods()
end

target 'RNTesterUnitTests' do
  pods()
  pod 'React-RCTTest', :path => "./RCTTest"
end

target 'RNTesterIntegrationTests' do
  pods()
  pod 'React-RCTTest', :path => "./RCTTest"
end

