name: Cut RNTV release branch

on:
  workflow_dispatch:
    inputs:
      release:
        type: string

defaults:
  tools:
    node: 22.14.0

jobs:
  cut_release_branch:
    name: Cut release branch
    runs_on: linux-medium
    image: latest
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - name: Cut release branch
        id: cut-release-branch
        run: |
          export REACT_NATIVE_RELEASE_VERSION=${{ inputs.release }}
          export REACT_NATIVE_RELEASE_BRANCH=release-${{ inputs.release }}
          export PUSH_RELEASE_TO_REPO=true
          npx tsx ./src/cut-release-branch.ts
