name: Publish RNTV release

jobs:
  build_apple_publish:
    name: Publish Apple artifacts to Maven Central
    type: build
    params:
      platform: ios
      profile: rncore-release-publish
  build_android_publish:
    name: Publish Android artifacts to Maven Central and create NPM tarballs
    needs: [build_apple_publish]
    type: build
    params:
      platform: android
      profile: android-artifacts-publish
