name: Run RNTV builds

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - packages/react-native/**
      - packages/react-native-codegen/**
      - packages/react-native-codegen-typescript-test/**
      - packages/rn-tester/**
      - packages/virtualized-lists/**
      - tools/rntv-workflows/**

concurrency:
  group: ${{ workflow.filename }}-${{ github.ref }}
  cancel_in_progress: true

jobs:
  build_apple:
    name: Create Apple artifacts
    type: build
    params:
      platform: ios
      profile: apple-artifacts-main
  ##### KEEP FOR TESTING #####
  # build_apple:
  #   name: Create Apple artifacts
  #   type: custom
  #   outputs:
  #     build_id: ${{ steps.run_script.outputs.build_id }}
  #   steps:
  #     - run_script:
  #       name: Run scripts
  #       id: run_script
  #       outputs: [build_id]
  #       run: |
  #         echo "Setting output to b9ce8d5a-4fc0-45df-9a21-83f4d03cfb8e"
  #         set-output build_id b9ce8d5a-4fc0-45df-9a21-83f4d03cfb8e
  build_rntester_apple_debug:
    name: Create Apple RNTester debug images
    type: build
    needs: [build_apple]
    env:
      ARTIFACTS_BUILD_ID: ${{ needs.build_apple.outputs.build_id }}
    params:
      platform: ios
      profile: rntester-apple-debug-main
  build_rntester_apple_release:
    name: Create Apple RNTester release images
    type: build
    needs: [build_apple]
    env:
      ARTIFACTS_BUILD_ID: ${{ needs.build_apple.outputs.build_id }}
    params:
      platform: ios
      profile: rntester-apple-release-main
  build_android:
    name: Create Android artifacts
    type: build
    params:
      platform: android
      profile: android-artifacts-main
  ##### KEEP FOR TESTING #####
  # build_android:
  #   name: Create Android artifacts
  #   type: custom
  #   outputs:
  #     build_id: ${{ steps.run_script.outputs.build_id }}
  #   steps:
  #     - run_script:
  #       name: Run scripts
  #       id: run_script
  #       outputs: [build_id]
  #       run: |
  #         echo "Setting output to 525376a4-2848-42ad-abce-046f352b400e"
  #         set-output build_id 525376a4-2848-42ad-abce-046f352b400e
  build_rntester_android:
    name: Create Android RNTester images
    type: build
    needs: [build_android]
    env:
      ARTIFACTS_BUILD_ID: ${{ needs.build_android.outputs.build_id }}
    params:
      platform: android
      profile: rntester-android-main
  build_npm_packages:
    name: Create NPM packages
    type: build
    needs: [build_rntester_android, build_rntester_apple_debug, build_rntester_apple_release]
    params:
      platform: android
      profile: npm-images-main


