name: Run RNTV builds

on:
  push:
    branches: [release-0.81*]

jobs:
  build_apple:
    name: Create Apple artifacts and RNTester
    type: build
    params:
      platform: ios
      profile: rncore-release
  build_android:
    name: Create Android artifacts and RNTester
    type: build
    params:
      platform: android
      profile: android-artifacts
