/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @flow
 * @format
 */

/**
 * Headers compose — emits the headers-spec layout (rules R1–R8 in
 * headers-spec.js) into a React.xcframework and builds the headers-only
 * ReactNativeHeaders.xcframework beside it (pure-RN: the third-party deps
 * namespaces ship in the ReactNativeDependenciesHeaders sidecar instead —
 * see headers-xcframework.js). The prebuild path (xcframework.js) composes
 * before signing (R7); `ensureHeadersLayout()` applies the same emission to
 * an already-cached artifact and builds the deps sidecar from the slot's
 * deps headers. One projector, spec-driven, byte-identical output either
 * way.
 */

const {
  buildI18nStringsBundle,
  buildReactPrivacyManifest,
  collectLprojDirs,
  serializePrivacyManifest,
} = require('./framework-resources');
const {computeInventory} = require('./headers-inventory');
const {
  DEPS_NAMESPACES,
  planFromInventory,
  renderNamespaceModuleMap,
  renderReactModuleMap,
  renderUmbrellaHeader,
} = require('./headers-spec');
const {
  CATALYST_STUB_SLICE,
  DEFAULT_STUB_SLICES,
  buildDepsHeadersXcframework,
  composeHeadersOnlyXcframework,
} = require('./headers-xcframework');
const {execFileSync} = require('child_process');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

// APFS clonefile (-c) is a macOS-only cp flag; plain -R elsewhere (Linux CI
// exercises these paths through the jest integration tests).
const CP_FLAGS = process.platform === 'darwin' ? '-Rc' : '-R';

// Hash of the compose tooling itself. Folded into the freshness marker so a
// local edit to any of these scripts (which changes the composed output)
// forces a recompose even when the cached source xcframework is untouched —
// the Info.plist mtime alone can't catch that. Stable across fresh checkouts
// (content-based, not mtime-based). sha256 to avoid weak-hash lint.
//
// This list must contain every local sibling module headers-compose.js
// requires (i.e. every `require('./*.js')` above) — the guard test in
// __tests__/headers-compose-test.js enforces that by parsing this file's
// source and diffing it against this list, so an added require without a
// matching entry here fails the test instead of silently going stale.
const COMPOSE_TOOLING_FILES /*: Array<string> */ = [
  'framework-resources.js',
  'headers-inventory.js',
  'headers-spec.js',
  'headers-xcframework.js',
  'headers-compose.js',
];

function composeToolingHash() /*: string */ {
  const hash = crypto.createHash('sha256');
  for (const name of COMPOSE_TOOLING_FILES) {
    hash.update(fs.readFileSync(path.join(__dirname, name)));
  }
  return hash.digest('hex');
}

/*:: import type {HeadersSpecPlan, SpecEntry} from './headers-spec'; */

/**
 * Computes the spec plan from the live source tree. Throws on collisions
 * (R8) — a collision means the spec and the source tree disagree and the
 * artifact must not be produced.
 */
function computeSpecPlan(rnRoot /*: string */) /*: HeadersSpecPlan */ {
  const inventory = computeInventory(rnRoot);
  // R8, part 1: two distinct sources mapping to the same natural Headers/ path.
  // addIdentity merges these and planFromInventory keeps only identities[0], so
  // the second source would be silently dropped. Fail closed instead.
  if (inventory.collisions.length > 0) {
    const detail = inventory.collisions
      .map(c => `${c.naturalPath} <- ${c.sources.join(', ')}`)
      .join('\n  ');
    throw new Error(
      `header-inventory natural-path collisions (R8):\n  ${detail}`,
    );
  }
  const plan = planFromInventory(inventory, rnRoot);
  // R8, part 2: two natural paths colliding on the same xcframework destination.
  if (plan.collisions.length > 0) {
    throw new Error(
      `headers-spec collisions (R8):\n  ${plan.collisions.join('\n  ')}`,
    );
  }
  return plan;
}

/**
 * Copies spec entries (each `{relPath, source}`) into a staging dir, creating
 * parent dirs. Shared by the React.framework and ReactNativeHeaders emission.
 */
function stageEntries(
  stage /*: string */,
  entries /*: Array<SpecEntry> */,
  rnRoot /*: string */,
) /*: void */ {
  for (const e of entries) {
    const dest = path.join(stage, e.relPath);
    fs.mkdirSync(path.dirname(dest), {recursive: true});
    if (e.redirectTo != null) {
      // R11: duplicate spelling of a source that lives elsewhere — emit a
      // redirect shim so the declarations exist in exactly one file (module
      // ownership and #import-once stay coherent across spellings).
      fs.writeFileSync(
        dest,
        `// @generated by headers-compose (R11): this spelling redirects to\n` +
          `// the content's single home so clang modules stay coherent.\n` +
          `#import <${e.redirectTo}>\n`,
      );
    } else {
      fs.copyFileSync(path.join(rnRoot, e.source), dest);
    }
  }
}

/**
 * Emits the React.framework side of the spec (R1, R4, R6) into every slice
 * of an xcframework: Headers root = React/ hoisted to root + bare aliases,
 * generated umbrella + framework module map. Replaces each slice's Headers
 * and Modules. The xcframework's ROOT Headers/ (the CocoaPods header surface)
 * is left untouched.
 */
function emitReactFrameworkHeaders(
  xcfwPath /*: string */,
  plan /*: HeadersSpecPlan */,
  rnRoot /*: string */,
) /*: void */ {
  const stage = fs.mkdtempSync(
    path.join(path.dirname(xcfwPath), '.react-stage-'),
  );
  stageEntries(stage, plan.react, rnRoot);
  fs.writeFileSync(
    path.join(stage, 'React-umbrella.h'),
    renderUmbrellaHeader(plan.umbrella),
  );

  // A slice is any entry carrying a React.framework. The framework as built by
  // xcodebuild -create-xcframework ships no Headers/ dir of its own — this
  // emission creates it (and replaces Modules), so detect by the framework, not
  // by a pre-existing Headers/.
  const slices = fs
    .readdirSync(xcfwPath)
    .filter(d => fs.existsSync(path.join(xcfwPath, d, 'React.framework')));

  // Aggregate the privacy manifests of the pods baked into React.framework into
  // one root-level PrivacyInfo.xcprivacy, so the prebuilt artifact carries them
  // for both CocoaPods-prebuilt and SwiftPM (source builds get them from the
  // podspecs instead). Built once, embedded per slice.
  const privacyManifest = buildReactPrivacyManifest(rnRoot);

  // Build RCTI18nStrings.bundle ONCE into a temp stage, then clone it into each
  // slice below — mirrors the privacy manifest (computed once, embedded per
  // slice) instead of rebuilding the bundle inside the slice loop. The stage is
  // only created when there are locales to bundle.
  let i18nStage = null;
  let i18nBundleStage = null;
  let i18nLocales = 0;
  if (collectLprojDirs(rnRoot).length > 0) {
    i18nStage = fs.mkdtempSync(
      path.join(path.dirname(xcfwPath), '.i18n-stage-'),
    );
    i18nBundleStage = path.join(i18nStage, 'RCTI18nStrings.bundle');
    i18nLocales = buildI18nStringsBundle(rnRoot, i18nBundleStage);
  }

  for (const slice of slices) {
    const fwk = path.join(xcfwPath, slice, 'React.framework');
    fs.rmSync(path.join(fwk, 'Headers'), {recursive: true, force: true});
    execFileSync('/bin/cp', [CP_FLAGS, stage, path.join(fwk, 'Headers')]);
    fs.rmSync(path.join(fwk, 'Modules'), {recursive: true, force: true});
    fs.mkdirSync(path.join(fwk, 'Modules'), {recursive: true});
    fs.writeFileSync(
      path.join(fwk, 'Modules', 'module.modulemap'),
      renderReactModuleMap(plan.privateReactHeaders),
    );
    if (privacyManifest != null) {
      fs.writeFileSync(
        path.join(fwk, 'PrivacyInfo.xcprivacy'),
        serializePrivacyManifest(privacyManifest),
      );
    }
    // Clone the prebuilt RCTI18nStrings.bundle so the framework-aware
    // RCTLocalizedString loader resolves React-Core's strings in prebuilt/SPM.
    if (i18nLocales > 0 && i18nBundleStage != null) {
      const dest = path.join(fwk, 'RCTI18nStrings.bundle');
      fs.rmSync(dest, {recursive: true, force: true});
      execFileSync('/bin/cp', [CP_FLAGS, i18nBundleStage, dest]);
    }
  }
  fs.rmSync(stage, {recursive: true, force: true});
  if (i18nStage != null) {
    fs.rmSync(i18nStage, {recursive: true, force: true});
  }
  console.log(
    `headers-compose: React.framework spec layout -> ${slices.join(', ')} ` +
      `(${plan.react.length} headers, umbrella ${plan.umbrella.length}` +
      `${privacyManifest != null ? ', +PrivacyInfo.xcprivacy' : ''}` +
      `${i18nLocales > 0 ? `, +RCTI18nStrings.bundle (${i18nLocales} locales)` : ''})`,
  );
}

/**
 * Builds ReactNativeHeaders.xcframework (R2, R5): a headers-only LIBRARY
 * xcframework (stub static archives — nothing embeds in apps) whose Headers
 * root carries every non-React RN namespace, plus module.modulemap with the
 * plain per-namespace modules. PURE-RN: the third-party deps namespaces ship
 * in the ReactNativeDependenciesHeaders sidecar built by the deps prebuild
 * (and by ensureHeadersLayout on the consumer side) — never here. SPM serves
 * its Headers automatically to dependents — no flags.
 */
function buildReactNativeHeadersXcframework(
  outDir /*: string */,
  plan /*: HeadersSpecPlan */,
  rnRoot /*: string */,
  includeCatalyst /*: boolean */ = false,
  // Optional dir containing a `hermes/` namespace (Hermes public headers from
  // the hermes-ios tarball's destroot/include). Folded in as a textual
  // namespace so `<hermes/...>` resolves without per-library wiring. null
  // when unstaged — then `<hermes/...>` stays unavailable.
  hermesHeaders /*: ?string */ = null,
) /*: string */ {
  // ---- stage headers ----
  const stage = fs.mkdtempSync(path.join(outDir, '.rnh-stage-'));
  stageEntries(stage, plan.reactNativeHeaders, rnRoot);
  // Hermes public headers (separate source from the deps namespaces — they
  // come from the hermes-ios tarball, not ReactNativeDependencies). Vend only
  // the `hermes/` namespace; `jsi/` is already provided elsewhere, so copying
  // it here would double-vend.
  let hermesFolded = false;
  if (hermesHeaders != null) {
    const src = path.join(hermesHeaders, 'hermes');
    if (fs.existsSync(src)) {
      execFileSync('/bin/cp', [CP_FLAGS, src, path.join(stage, 'hermes')]);
      hermesFolded = true;
    } else {
      console.warn(
        `headers-compose: hermes headers missing at ${src} — the composed ` +
          'ReactNativeHeaders will NOT resolve <hermes/...>; a downstream ' +
          'build that imports Hermes headers will fail. Ensure the hermes-ios ' +
          "tarball's destroot/include was staged into the slot.",
      );
    }
  }
  // R10: per-namespace umbrella headers (e.g. React_RCTAppDelegate-umbrella.h)
  // that consumers like Expo probe via __has_include. Must be staged before the
  // module map references them.
  for (const u of plan.namespaceUmbrellas) {
    const dest = path.join(stage, u.relPath);
    fs.mkdirSync(path.dirname(dest), {recursive: true});
    fs.writeFileSync(dest, u.content);
  }
  fs.writeFileSync(
    path.join(stage, 'module.modulemap'),
    renderNamespaceModuleMap(plan.namespaceModules),
  );

  // ---- compose (stub archives + create-xcframework) ----
  const slices = includeCatalyst
    ? [...DEFAULT_STUB_SLICES, CATALYST_STUB_SLICE]
    : DEFAULT_STUB_SLICES;
  const outXcfw = composeHeadersOnlyXcframework(
    outDir,
    'ReactNativeHeaders',
    stage,
    slices,
  );
  fs.rmSync(stage, {recursive: true, force: true});
  console.log(
    `headers-compose: ReactNativeHeaders.xcframework (${slices.map(s => s.name).join(', ')}) -> ${outXcfw} ` +
      `(${plan.reactNativeHeaders.length} RN headers, pure-RN` +
      `${hermesFolded ? ' + hermes' : ''}; ` +
      `${Object.keys(plan.namespaceModules).length} namespace modules)`,
  );
  return outXcfw;
}

/**
 * Ensures the headers-spec layout exists at `outDir`, composed from the cache
 * slot's artifacts: clones React.xcframework (APFS clonefile), strips the
 * stale signature (R7 — production signs after compose), emits the spec
 * layout into every slice, builds the pure-RN ReactNativeHeaders.xcframework
 * from the plan, and builds the ReactNativeDependenciesHeaders sidecar from
 * the slot's deps headers.
 *
 * Skips when the freshness marker matches the source artifact (same
 * realpath + Info.plist mtime) unless `force`. Any consumer with a cache slot
 * gets composed artifacts automatically — no published ReactNativeHeaders /
 * ReactNativeDependenciesHeaders required.
 */
function ensureHeadersLayout(
  artifactsDir /*: string */,
  rnRoot /*: string */,
  outDir /*: string */,
  force /*: boolean */ = false,
) /*: {reactXcfw: string, headersXcfw: string, depsHeadersXcfw: string} */ {
  const sourceXcfw = fs.realpathSync(
    path.join(artifactsDir, 'React.xcframework'),
  );
  const depsHeaders = path.join(
    artifactsDir,
    'ReactNativeDependencies.xcframework',
    'Headers',
  );
  // Hermes public headers staged into the slot by download-spm-artifacts
  // (the hermes-ios tarball ships them in destroot/include, which the
  // xcframework extraction otherwise discards). null when absent — then
  // ReactNativeHeaders composes without the hermes namespace.
  const hermesHeadersDir = path.join(artifactsDir, 'hermes-headers');
  const hermesHeaders = fs.existsSync(path.join(hermesHeadersDir, 'hermes'))
    ? hermesHeadersDir
    : null;
  const reactXcfw = path.join(outDir, 'React.xcframework');
  const headersXcfw = path.join(outDir, 'ReactNativeHeaders.xcframework');
  const depsHeadersXcfw = path.join(
    outDir,
    'ReactNativeDependenciesHeaders.xcframework',
  );
  const markerPath = path.join(outDir, '.composed-from');

  const sourceStat = fs.statSync(path.join(sourceXcfw, 'Info.plist'));
  // Fold the hermes-headers presence into the marker so a slot that gains
  // staged hermes headers (e.g. after a tooling upgrade re-downloads them)
  // recomposes instead of reusing a hermes-less ReactNativeHeaders. The
  // compose-tooling hash makes a local edit to headers-{inventory,spec,compose}
  // recompose too (the source xcframework's Info.plist mtime can't detect that).
  const marker = `${sourceXcfw}\n${sourceStat.mtimeMs}\n${hermesHeaders ?? 'no-hermes'}\ntooling:${composeToolingHash()}\n`;
  if (
    !force &&
    fs.existsSync(reactXcfw) &&
    fs.existsSync(headersXcfw) &&
    fs.existsSync(depsHeadersXcfw) &&
    fs.existsSync(markerPath) &&
    fs.readFileSync(markerPath, 'utf8') === marker
  ) {
    return {reactXcfw, headersXcfw, depsHeadersXcfw};
  }

  console.log(
    `headers-compose: composing layout from ${path.basename(artifactsDir)} slot...`,
  );
  fs.rmSync(reactXcfw, {recursive: true, force: true});
  fs.rmSync(markerPath, {force: true});
  fs.mkdirSync(outDir, {recursive: true});
  execFileSync('/bin/cp', [CP_FLAGS, sourceXcfw, reactXcfw]);
  fs.rmSync(path.join(reactXcfw, '_CodeSignature'), {
    recursive: true,
    force: true,
  });

  const plan = computeSpecPlan(rnRoot);
  emitReactFrameworkHeaders(reactXcfw, plan, rnRoot);
  buildReactNativeHeadersXcframework(
    outDir,
    plan,
    rnRoot,
    false,
    hermesHeaders,
  );
  // The deps sidecar (like ReactNativeHeaders here) skips the catalyst slice
  // on the consumer repackage path to stay fast.
  buildDepsHeadersXcframework(
    outDir,
    depsHeaders,
    plan.depsNamespaces,
    DEFAULT_STUB_SLICES,
  );
  fs.writeFileSync(markerPath, marker);
  return {reactXcfw, headersXcfw, depsHeadersXcfw};
}

module.exports = {
  computeSpecPlan,
  emitReactFrameworkHeaders,
  buildReactNativeHeadersXcframework,
  ensureHeadersLayout,
  DEPS_NAMESPACES,
  COMPOSE_TOOLING_FILES,
  composeToolingHash,
};
